### ISSUE TITLE
$ionicProfile and $ionicAPIToken examples

### ISSUE THREAD

**Issue by gamboaweb** [tomloprod/ionic-push-php#1]
Hello tomloprod,
your script seems very nice but as it is my first ionic project i was wondering what should i fill as $ionicProfile (is it a JSON object?) could you be more specific? And what about $ionicAPIToken...it's a string wright....??....but in the app settings in ionic dashboard there is public api key and a secret api key....which of them should i use as $ionicAPIToken...
Thanks for your support.

**Comment by tomloprod** [comment]
Hi @gamboaweb 

`$ionicProfile` is a string. It's the profile name of your certificate. Go to [ionic.io](http://ionic.io/) and access to `Settings` tab. Inside this, you will see a menu like this:

<img src="https://cloud.githubusercontent.com/assets/7898894/21962900/f83252bc-db2f-11e6-87ce-3f8b89cb575d.png" width="100px" style="width:100px;">

In the `certificates` section you will have your certificates (*for production and development purposes*). The `$ionicProfile` is the name of your certificate.

---

`$ionicAPIToken` is a string too. It's the API token that you can create inside the `API Keys` section from the same menu as the previous image:

<img src="https://cloud.githubusercontent.com/assets/7898894/21962933/6f4bad1c-db30-11e6-8175-ef7e36eb4c13.png" width="500px" style="width:500px;">

**Comment by tomloprod** [comment]
@gamboaweb This solve your doubt?

**Comment by gamboaweb** [comment]
Thanks a lot... i wouldn't have guessed it was the certificate tag.
Thanks for the quick reply....i am gonna test it right now.
Have a good sunday.

**Comment by tomloprod** [comment]
Don't worry; glad to have help. And, if my script help you, please, give it a star :-)
