### ISSUE TITLE
ApiResponse::__construct() must be an instance of Tomloprod\IonicApi\Api\number, integer given

### ISSUE THREAD

**Issue by anibalsanchez** [tomloprod/ionic-push-php#11]
Hi,

In PHP 7.0.15, it does not accept the type declaration. Removing the number type from the __construct solves the issue.

**Comment by tomloprod** [comment]
Hi @anibalsanche.

I know. In the commit of four days ago I have removed this declaration.

Thank you. :-)

Regards,
