### ISSUE TITLE
Expand library with Deploy and Auth endpoints?

### ISSUE THREAD

**Issue by ramoncarreras** [tomloprod/ionic-push-php#14]
We can make this library more generic and implement methods for [Auth API](https://docs.ionic.io/api/endpoints/auth.html) and [Deploy API](https://docs.ionic.io/api/endpoints/deploy.html).

The library name could be:
- ionic-api-php
- ionic-html-api-php
- ionic-cloud-api-php
- ...

**Comment by tomloprod** [comment]
Another name could be:

- ionic-cloud-php

`ionic-api-php` it's ok too.

**Comment by tomloprod** [comment]
I have created `ionic-cloud-php` repo, to make some tests at weekend. I wil try with [Deploy API](https://docs.ionic.io/api/endpoints/deploy.html) first.

**Comment by ramoncarreras** [comment]
Great!

**Comment by tomloprod** [comment]
I close this issue, because we have a new repository for that: https://github.com/tomloprod/ionic-cloud-php
