### ISSUE TITLE
Invalid JSON on deviceTokens create action

### ISSUE THREAD

**Issue by eusonlito** [tomloprod/ionic-push-php#16]
With this code:

```php
$api = new BasePush(env('IONIC_API_PROFILE'), env('IONIC_API_KEY'));

$api->deviceTokens->create([
    'token' => (string)$token,
    'user_id' => (string)$user->id
]);
```

I get

```json
{
"code": "error",
"message": "Invalid JSON in request body. For empty JSON, pass '{}'."
}
```

Thanks!

**Comment by tomloprod** [comment]
Hi,

Maybe you are using some abnormal characters in your `$token` variable? (like `’`, `”`, ...)

Regards,

**Comment by eusonlito** [comment]
device id returned by ionic compiled app is `cxNNtw4NHL5:APA91bEGadiR9CMi2hzDHG7A3Hi2ire5iAVnsuiIaSJFRNK-vJs8Y2tgXqlsYtcd3fKyZmgCSqT8JCJn59yVonhcDLxjKNc4EE7IZwuVTDRACUxmxwG5wbvYYjktw3qcdH7-0oJNEsly`

**Comment by eusonlito** [comment]
With a fixed token and id also fail with same error:

```php
$api->deviceTokens->create([
    'token' => 'cxNNtw4NHL5',
    'user_id' => 'cxNNtw4NHL5'
]);
```

This code is working without problems:

```php
$api->notifications->sendNotificationToAll();
```

**Comment by tomloprod** [comment]
Hi @eusonlito 

I will take a look at this when I finish at work. (_same for your other issue_)

Regards,

**Comment by eusonlito** [comment]
Perfect :)

Thanks!!

**Comment by tomloprod** [comment]
I don't forgot you, but until the weekend Im very busy :-(

**Comment by eusonlito** [comment]
Ok, no problem :)

**Comment by eusonlito** [comment]
Some debug:

```php
$api->deviceTokens->create([
    'token' => (string)$token,
    'user_id' => (string)$user->id
]);
```
```php
class Tomloprod\IonicApi\Api\DeviceTokens

public function create($parameters) {
    return $this->sendRequest(
        self::METHOD_POST,
        self::$endPoints['create'] . '?' . http_build_query($parameters)
    );
}
```

```php
class Tomloprod\IonicApi\Api\Request

public function sendRequest($method, $endPoint, $data = "") {
    $jsonData = json_encode($data);
...
    if(!empty($jsonData)) { // POST REQUEST AND EMPTY DATA
        curl_setopt($curlHandler, CURLOPT_POSTFIELDS, $jsonData);
    }
```

POST request parameters are not on body, are on GET query, then the body request is empty.

POST parameters must be added to BODY https://docs.ionic.io/api/endpoints/push.html#post-tokens

**Comment by tomloprod** [comment]
Thank you for your PR! :-)
