### ISSUE TITLE
Fatal error: Uncaught Error: Class 

### ISSUE THREAD

**Issue by whatnowangga** [tomloprod/ionic-push-php#18]
got this error
whats wrong ???
http://prntscr.com/fbmyup

**Comment by tomloprod** [comment]
Have you installed this package with composer?

    composer require tomloprod/ionic-push-php

**Comment by whatnowangga** [comment]
yes,
i dont know to using "namespace" or use \bla\bla .
please help :(

**Comment by whatnowangga** [comment]
this is my folder structure
http://prntscr.com/fbn5k8

**Comment by tomloprod** [comment]
In your index.php, add the next code at the top:

    require __DIR__ . '/vendor/autoload.php';

So composers will work.

**Comment by whatnowangga** [comment]
yes, that is worked. thanks

and then i got this error 

http://prntscr.com/fbnf3z

**Comment by whatnowangga** [comment]
ups my bad, 
didnt read the Exception.
thanks before, all is working right now .
