### ISSUE TITLE
Unable to Delete

### ISSUE THREAD

**Issue by kevinmikol** [tomloprod/ionic-push-php#7]
I want to delete all notifications in Ionic.  The code I'm using is below:

	`$notificationsarr = json_decode( $notifications , true);
	foreach($notificationsarr as $notification){
		foreach($notification as $item){
			$deleteResult = $ionicPushApi->messages->delete($item['uuid']);
		}
	}`

I keep getting a 404 error with "notification with that uuid does not exist". Even if I run the function by directly injecting a notification uuid, it returns the same results.

**Comment by tomloprod** [comment]
That code is for delete `messages`, not `notifications`. Use this instead:

`$deleteResult = $ionicPushApi->notifications->delete($item['uuid']);`

**Comment by kevinmikol** [comment]
Oh duh - that makes sense. Thank you! Can you explain a little about Notifications vs. Messages?

**Comment by tomloprod** [comment]
You're welcome :-)  Of course:

- **Notification:** The push notification you can send to your users.
- **Message:** It's a message generated from the Ionic Push Server when you send a notification. It's like a state for each notification.  By consulting the message of a notification you can know the current status of the notification, if an error has occurred, etc.

Here the official description of a message: http://docs.ionic.io/services/push/#checking-notification-status.

Here you can see the possible errors returned by a message: https://docs.ionic.io/api/endpoints/push.html#get-messages-message_id

Please, tell me if  now you can delete your notifications and I will close this issue.

Regards!

**Comment by kevinmikol** [comment]
Thank you! I think I'm still having a similar issue. I'm currently iterating through all the notifications and then having them delete.. however, when I go to list them, they still appear.

`$notificationsarr = json_decode( $notifications , true);
        foreach($notificationsarr as $notification){
            foreach($notification as $item){
                echo $deleteResult = $ionicPushApi->notifications->delete($item['uuid']);
            }
        } 
        echo "<br /><br /><hr />LIST ALL: ";
        echo $notifications = $ionicPushApi->notifications->paginatedList([
            // Sets the number of items to return per page (integer)
            'page_size' => 10000,
            // Sets the page number (integer)
            'page' => 1,
            // You can also pass other fields like "message_total" or "overview" (string[])
            'fields' => [
                'message_total'
            ]
        ]);`

**Comment by tomloprod** [comment]
Okey! I will take a look when get home :-)

**Comment by tomloprod** [comment]
Well, I tried to **retrieve**, **remove** and then **retrieve again** a notification and **all works well.**

The first time I see the notification data and after delete I get a JSON Object with the error, like this:
```json
{
   "error": {
        "type": "NotFound", 
        "message": "Unable to find a notification with the specified uuid", 
        "link": null
    },
    "meta": {
        "version": "2.0.0-beta.0", 
        "status": 404, 
        "request_id": "3bcc..."
    }
}
```

So `notifications->delete()` method works well. Try to use it outside the `foreach` and tell me if works.

**Comment by tomloprod** [comment]
And by the way, your code doesn't look very well. Try with something like this:

```php
<ul>
    <?php
    $response = $ionicPushApi->notifications->paginatedList(['page_size' => 10000, 'page' => 1]);
    $notifications = json_decode($response);
    // Sometimes, on fast requests, response could be null.
    if($notifications !== null){
        foreach($notifications->data as $notification){
    ?>
            <li><pre> <?php var_dump($notification); ?> </pre></li>
    <?php 
        }
    } else {
    ?>
            <li>Response is null!</li>
    <?php
    }
    ?>
</ul>
```

**Comment by kevinmikol** [comment]
Seems to still not work well with your suggested code - http://bradleyinteractive.com/mocsat-api/notify.php

**Comment by tomloprod** [comment]
@kevinmikol My code suggestion it's only for show the notifications. Are you using the delete before that, no?

**Comment by kevinmikol** [comment]
Yeah I am -

The way I'm doing it is with
````php
$notificationsarr = json_decode( $notifications , true);
foreach($notificationsarr as $notification){
    foreach($notification as $item){
        $deleteResult = $ionicPushApi->notifications->delete($item['uuid']);
    }
}
````
But that seems to not work.

Sorry about formatting - GitHub keeps changing it on me.

**Comment by tomloprod** [comment]
Don't worry about format, I updated your comment. :-)

Try with this:
```php
// Get all notifications (since we do not pass pagination parameters):
$response = $ionicPushApi->notifications->paginatedList();
// Decode JSON:
$notifications = json_decode($response);
// If is an object with data, we loop through each notification:
if(is_object($notifications) && property_exists($notifications, "data")) {
    foreach($notifications->data as $notification) {
        // Delete notification
        $ionicPushApi->notifications->delete($notification->uuid);
    }
} else {
    echo "Response is null";
}
```

Regards,

**Comment by kevinmikol** [comment]
Hey! That worked perfectly. Thanks for all the help.

**Comment by tomloprod** [comment]
@kevinmikol Okey! You're welcome. Please try with the new method `deleteAll`:

```php
$ionicPushApi->notifications->deleteAll();
```

I made it for you! Tell me if works :-)

Regards,

**Comment by kevinmikol** [comment]
Works for me!

**Comment by kevinmikol** [comment]
Take that back - 
Warning: Invalid argument supplied for foreach() in /src/Api/Notifications.php on line 133

**Comment by tomloprod** [comment]
@kevinmikol Yes, there was a little bug  (*when there is no notifications and call `deleteAll`*). 

I solved this issue. Try and tell me if is ok.

**Comment by kevinmikol** [comment]
Worked perfectly!
